services:
  db:
    image: mysql:8.0
    container_name: db 
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME:-rbac}  
      MYSQL_USER: ${DB_USER:-user}      
      MYSQL_PASSWORD: ${DB_PASSWORD:-test123}  
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - rbac-network

  backend:
    build:
      context: ./be 
    container_name: rbac-be
    env_file:
      - ./be/.env  
    environment:
      MYSQL_HOST: ${DB_HOST:-db} 
      MYSQL_USER: ${DB_USER:-user}  
      MYSQL_PASSWORD: ${DB_PASSWORD:-test123} 
      MYSQL_DATABASE: ${DB_NAME:-rbac}  
      JWT_SECRET: ${JWT_SECRET:-rbac-secret-key}  
    ports:
      - "${PORT:-5000}:${PORT:-5000}" 
    depends_on:
      - db
    networks:
      - rbac-network

networks:
  rbac-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
