services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME:-rbac}  
      MYSQL_USER: ${DB_USER:-user}      
      MYSQL_PASSWORD: ${DB_PASSWORD:-test123}  
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - rbac-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=rootpassword"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always  # Optionally add to restart container if unhealthy

  backend:
    build:
      context: ./be
    container_name: rbac-be
    env_file:
      - ./be/.env  
    environment:
      MYSQL_HOST: ${DB_HOST:-db} 
      MYSQL_USER: ${DB_USER:-user}  
      MYSQL_PASSWORD: ${DB_PASSWORD:-test123} 
      MYSQL_DATABASE: ${DB_NAME:-rbac}  
      JWT_SECRET: ${JWT_SECRET:-rbac-secret-key}  
    ports:
      - "${PORT:-5000}:${PORT:-5000}" 
    depends_on:
      - db
    networks:
      - rbac-network
    volumes:
      - ./be/src:/app/backend/src

networks:
  rbac-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
